; ============================================================
; DEAL OR NO DEAL - NES homebrew
; ============================================================

.segment "HEADER"
    .byte "NES", $1A
    .byte 2        ; 2 * 16KB PRG
    .byte 1        ; 1 * 8KB CHR
    .byte $01      ; mapper 0, vertical mirroring
    .byte $00
    .byte 0,0,0,0,0,0,0,0

; ------------------------------------------------------------
; Custom charmap: map ASCII chars used in string literals to
; our tile indices generated by gen_chr.cjs
; ------------------------------------------------------------
.charmap $20, 0        ; space
.charmap $41, 1  ; A
.charmap $42, 2  ; B
.charmap $43, 3  ; C
.charmap $44, 4  ; D
.charmap $45, 5  ; E
.charmap $46, 6  ; F
.charmap $47, 7  ; G
.charmap $48, 8  ; H
.charmap $49, 9  ; I
.charmap $4A, 10 ; J
.charmap $4B, 11 ; K
.charmap $4C, 12 ; L
.charmap $4D, 13 ; M
.charmap $4E, 14 ; N
.charmap $4F, 15 ; O
.charmap $50, 16 ; P
.charmap $51, 17 ; Q
.charmap $52, 18 ; R
.charmap $53, 19 ; S
.charmap $54, 20 ; T
.charmap $55, 21 ; U
.charmap $56, 22 ; V
.charmap $57, 23 ; W
.charmap $58, 24 ; X
.charmap $59, 25 ; Y
.charmap $5A, 26 ; Z
.charmap $30, 27 ; 0
.charmap $31, 28 ; 1
.charmap $32, 29 ; 2
.charmap $33, 30 ; 3
.charmap $34, 31 ; 4
.charmap $35, 32 ; 5
.charmap $36, 33 ; 6
.charmap $37, 34 ; 7
.charmap $38, 35 ; 8
.charmap $39, 36 ; 9
.charmap $24, 37 ; $
.charmap $2C, 38 ; ,
.charmap $2E, 39 ; .
.charmap $3A, 40 ; :
.charmap $3F, 41 ; ?
.charmap $21, 42 ; !
.charmap $2D, 43 ; -

TILE_SPACE   = 0
TILE_SOLID   = 44
TILE_CASE    = 45
TILE_CURSOR  = 46

BTN_A      = $80
BTN_B      = $40
BTN_SELECT = $20
BTN_START  = $10
BTN_UP     = $08
BTN_DOWN   = $04
BTN_LEFT   = $02
BTN_RIGHT  = $01

ST_TITLE      = 0
ST_PICK_OWN   = 1
ST_PICK_OPEN  = 2
ST_OFFER      = 3
ST_FINAL_SWAP = 4
ST_GAMEOVER   = 5

; ------------------------------------------------------------
; Zero page variables
; ------------------------------------------------------------
.segment "ZEROPAGE"
nmi_flag:       .res 1
frame_counter:  .res 1
pad1:           .res 1
pad1_old:       .res 1
pad1_new:       .res 1
game_state:     .res 1
cursor:         .res 1
last_cursor:    .res 1
own_case:       .res 1
round_idx:      .res 1
cases_left:     .res 1
final_other:    .res 1
chosen_case:    .res 1
rng:            .res 1

ptr_lo:         .res 1
ptr_hi:         .res 1
ppu_lo:         .res 1
ppu_hi:         .res 1
tmp_row:        .res 1
tmp_col:        .res 1
tmp_a:          .res 1
tmp_b:          .res 1
loop_i:         .res 1
loop_j:         .res 1

sum_lo:         .res 1
sum_hi:         .res 1
count8:         .res 1
quot_lo:        .res 1
quot_hi:        .res 1
digit0:         .res 1
digit1:         .res 1
digit2:         .res 1
digit3:         .res 1
digit4:         .res 1

; ------------------------------------------------------------
; RAM arrays
; ------------------------------------------------------------
.segment "BSS"
case_value:     .res 10   ; value-index (0-9) assigned to each case slot
case_opened:    .res 10   ; 0/1
offer_lo:       .res 1
offer_hi:       .res 1
offer_str:      .res 8    ; '$' + up to 5 digits + terminator
open_num_buf:   .res 2

; ------------------------------------------------------------
.segment "CODE"

RESET:
    sei
    cld
    ldx #$40
    stx $4017
    ldx #$FF
    txs
    inx             ; X = 0
    stx $2000
    stx $2001
    stx $4010

vblankwait1:
    bit $2002
    bpl vblankwait1

    ; clear RAM
clear_ram:
    lda #0
    sta $0000,x
    sta $0100,x
    sta $0300,x
    sta $0400,x
    sta $0500,x
    sta $0600,x
    sta $0700,x
    lda #$FE
    sta $0200,x     ; sprite ram (unused, park off-screen)
    inx
    bne clear_ram

vblankwait2:
    bit $2002
    bpl vblankwait2

    ; load palette
    lda $2002
    lda #$3F
    sta $2006
    lda #$00
    sta $2006
    ldx #0
load_pal:
    lda palette,x
    sta $2007
    inx
    cpx #32
    bne load_pal

    ; clear nametable 0 + attribute table to 0
    lda $2002
    lda #$20
    sta $2006
    lda #$00
    sta $2006
    lda #0
    ldx #4          ; 4 pages of 256 = 1024 bytes
clear_nt_page:
    ldy #0
clear_nt_byte:
    sta $2007
    iny
    bne clear_nt_byte
    dex
    bne clear_nt_page

    lda #1
    sta rng

    lda #$88
    sta $2000       ; NMI on, bg pattern table 0, sprites table 0
    lda #$00
    sta $2001       ; rendering off for now

    lda #ST_TITLE
    sta game_state
    jsr draw_title_screen

    jsr restore_scroll
    lda #$1E
    sta $2001       ; enable bg + sprites rendering (leftmost col too)

main_loop:
    jsr wait_vblank
    jsr read_pads
    jsr do_state
    jmp main_loop

; ------------------------------------------------------------
NMI:
    pha
    txa
    pha
    tya
    pha

    inc nmi_flag
    inc frame_counter

    pla
    tay
    pla
    tax
    pla
    rti

IRQ:
    rti

; ------------------------------------------------------------
; restore_scroll: resets the PPU address latch and scroll regs
; to (0,0). Must be called before re-enabling rendering any time
; $2006/$2007 were used, since they share internal PPU registers
; with the scroll position.
; ------------------------------------------------------------
restore_scroll:
    lda $2002
    lda #0
    sta $2005
    sta $2005
    rts

; ------------------------------------------------------------
wait_vblank:
    lda nmi_flag
@loop:
    cmp nmi_flag
    beq @loop
    rts

; ------------------------------------------------------------
read_pads:
    lda pad1
    sta pad1_old

    lda #1
    sta $4016
    lda #0
    sta $4016

    ldx #8
    lda #0
    sta tmp_a
@loop:
    lda $4016
    lsr a
    rol tmp_a
    dex
    bne @loop
    lda tmp_a
    sta pad1

    lda pad1
    eor pad1_old
    and pad1
    sta pad1_new
    rts

; ------------------------------------------------------------
do_state:
    lda game_state
    cmp #ST_TITLE
    bne @s1
    jmp state_title
@s1:
    cmp #ST_PICK_OWN
    bne @s2
    jmp state_pick_own
@s2:
    cmp #ST_PICK_OPEN
    bne @s3
    jmp state_pick_open
@s3:
    cmp #ST_OFFER
    bne @s4
    jmp state_offer
@s4:
    cmp #ST_FINAL_SWAP
    bne @s5
    jmp state_final_swap
@s5:
    jmp state_gameover

; ============================================================
; STATE: TITLE
; ============================================================
state_title:
    lda pad1_new
    and #BTN_START
    beq @done
    jsr init_game
@done:
    rts

; ============================================================
; STATE: PICK OWN CASE
; ============================================================
state_pick_own:
    jsr handle_cursor_move

    lda pad1_new
    and #BTN_A
    beq @done

    lda cursor
    sta own_case

    lda #ST_PICK_OPEN
    sta game_state
    lda #0
    sta round_idx
    lda round_sched
    sta cases_left

    jsr move_cursor_to_valid
    jsr draw_open_prompt
@done:
    rts

; ============================================================
; STATE: PICK CASES TO OPEN
; ============================================================
state_pick_open:
    jsr handle_cursor_move

    lda pad1_new
    and #BTN_A
    beq @done

    ; validate: not own_case, not already opened
    lda cursor
    cmp own_case
    beq @done
    ldx cursor
    lda case_opened,x
    bne @done

    ; open it
    lda #1
    sta case_opened,x
    jsr draw_case_value

    ; subtract its value from remaining sum, decrement count
    ldx cursor
    lda case_value,x
    tax
    lda sum_lo
    sec
    sbc values_lo,x
    sta sum_lo
    lda sum_hi
    sbc values_hi,x
    sta sum_hi
    dec count8

    dec cases_left
    lda cases_left
    bne @continue_round

    ; round finished - compute offer
    jsr compute_offer
    lda #ST_OFFER
    sta game_state
    jsr draw_offer_screen
    rts

@continue_round:
    jsr draw_open_prompt
@done:
    rts

; ============================================================
; STATE: OFFER (deal or no deal)
; ============================================================
state_offer:
    lda pad1_new
    and #BTN_A
    beq @check_b
    ; DEAL - take the offer
    lda offer_lo
    sta sum_lo         ; reuse sum as "final winnings" holder for reveal
    lda offer_hi
    sta sum_hi
    jsr draw_deal_result
    lda #ST_GAMEOVER
    sta game_state
    rts

@check_b:
    lda pad1_new
    and #BTN_B
    beq @done

    inc round_idx
    lda round_idx
    cmp #3
    bcc @next_round

    ; all main rounds done -> find final_other_case, go to swap stage
    jsr find_final_other
    lda #ST_FINAL_SWAP
    sta game_state
    jsr draw_swap_prompt
    rts

@next_round:
    ldx round_idx
    lda round_sched,x
    sta cases_left
    lda #ST_PICK_OPEN
    sta game_state
    jsr move_cursor_to_valid
    jsr draw_open_prompt
@done:
    rts

; ============================================================
; STATE: FINAL SWAP DECISION
; ============================================================
state_final_swap:
    lda pad1_new
    and #BTN_A
    beq @check_b
    lda own_case
    sta chosen_case
    jmp @reveal
@check_b:
    lda pad1_new
    and #BTN_B
    beq @done
    lda final_other
    sta chosen_case
@reveal:
    ldx chosen_case
    lda case_value,x
    tax
    lda values_lo,x
    sta sum_lo
    lda values_hi,x
    sta sum_hi
    jsr draw_final_result
    lda #ST_GAMEOVER
    sta game_state
@done:
    rts

; ============================================================
; STATE: GAME OVER (wait for start to restart)
; ============================================================
state_gameover:
    lda pad1_new
    and #BTN_START
    beq @done
    lda #$00
    sta $2001
    jsr clear_message_rows
    lda #ST_TITLE
    sta game_state
    jsr draw_title_screen
    jsr restore_scroll
    lda #$1E
    sta $2001
@done:
    rts

; ============================================================
; find_final_other: scans case_opened[] for the one case that
; is not opened and not own_case
; ============================================================
find_final_other:
    ldx #0
@loop:
    cpx own_case
    beq @skip
    lda case_opened,x
    bne @skip
    stx final_other
    rts
@skip:
    inx
    cpx #10
    bne @loop
    rts

; ============================================================
; move_cursor_to_valid: move cursor to the next unopened,
; non-own case (search forward, wrap)
; ============================================================
move_cursor_to_valid:
    ldx #0
@loop:
    cpx own_case
    beq @skip
    lda case_opened,x
    bne @skip
    stx cursor
    jsr redraw_cursor
    rts
@skip:
    inx
    cpx #10
    bne @loop
    rts

; ============================================================
; handle_cursor_move: reads pad1_new for dpad, updates cursor
; grid is 2 rows x 5 cols
; ============================================================
handle_cursor_move:
    lda cursor
    ldx #0
@rowloop:
    cmp #5
    bcc @gotrow
    sbc #5
    inx
    jmp @rowloop
@gotrow:
    sta tmp_col
    stx tmp_row

    lda pad1_new
    and #BTN_RIGHT
    beq @tryleft
    inc tmp_col
    lda tmp_col
    cmp #5
    bne @recalc
    lda #0
    sta tmp_col
    jmp @recalc

@tryleft:
    lda pad1_new
    and #BTN_LEFT
    beq @tryud
    lda tmp_col
    bne @decok
    lda #5
@decok:
    sec
    sbc #1
    sta tmp_col
    jmp @recalc

@tryud:
    lda pad1_new
    and #(BTN_UP | BTN_DOWN)
    beq @none
    lda tmp_row
    eor #1
    sta tmp_row
    jmp @recalc

@none:
    rts

@recalc:
    lda tmp_row
    asl a
    asl a
    clc
    adc tmp_row
    clc
    adc tmp_col
    sta cursor
    jsr redraw_cursor
    rts

; ============================================================
; redraw_cursor: clears old cursor tile, draws new one
; ============================================================
redraw_cursor:
    lda last_cursor
    cmp #$FF
    beq @drawnew
    tax
    lda case_row_cur,x
    sta tmp_row
    lda case_col,x
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    lda #TILE_SPACE
    sta $2007
    jsr restore_scroll
    lda #$1E
    sta $2001

@drawnew:
    ldx cursor
    lda case_row_cur,x
    sta tmp_row
    lda case_col,x
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    lda #TILE_CURSOR
    sta $2007
    jsr restore_scroll
    lda #$1E
    sta $2001

    lda cursor
    sta last_cursor
    rts

; ============================================================
; calc_ppu_addr: input tmp_row, tmp_col -> ppu_hi/ppu_lo
; addr = $2000 + row*32 + col
; ============================================================
calc_ppu_addr:
    lda tmp_row
    sta tmp_a
    lda #0
    sta tmp_b
    ldx #5
@shift:
    asl tmp_a
    rol tmp_b
    dex
    bne @shift
    lda tmp_a
    clc
    adc tmp_col
    sta ppu_lo
    lda tmp_b
    adc #$20
    sta ppu_hi
    rts

; ============================================================
; init_game: shuffle cases, reset state, draw game screen
; ============================================================
init_game:
    lda #$00
    sta $2001

    ; seed rng using frame_counter (never zero)
    lda frame_counter
    ora #1
    sta rng

    ; identity fill
    ldx #0
@fill:
    txa
    sta case_value,x
    lda #0
    sta case_opened,x
    inx
    cpx #10
    bne @fill

    ; fisher-yates shuffle: for i = 9 downto 1, j = rand(0..i)
    ldx #9
@shuffle:
    stx loop_i
    inx                  ; range = i+1
    txa
    jsr rand_range        ; returns A = rand in [0, range)
    sta loop_j

    ldx loop_i
    lda case_value,x
    sta tmp_a
    ldy loop_j
    lda case_value,y
    sta case_value,x
    lda tmp_a
    sta case_value,y

    ldx loop_i
    dex
    cpx #0
    beq @doneshuffle
    jmp @shuffle
@doneshuffle:

    lda #$FF
    sta own_case
    sta last_cursor
    lda #0
    sta cursor
    sta round_idx

    lda #<26661
    sta sum_lo
    lda #>26661
    sta sum_hi
    lda #10
    sta count8

    lda #ST_PICK_OWN
    sta game_state

    jsr draw_game_screen
    jsr restore_scroll
    lda #$1E
    sta $2001
    rts

; ============================================================
; rand_range: input A = range (1..10), output A = rand in [0,range)
; updates rng (8-bit LFSR)
; ============================================================
rand_range:
    sta tmp_b            ; save range
    lda rng
    lsr a
    bcc @noeor
    eor #$B4
@noeor:
    sta rng
@modloop:
    cmp tmp_b
    bcc @done
    sbc tmp_b
    jmp @modloop
@done:
    rts

; ============================================================
; compute_offer: sum_lo/hi divided by count8 -> offer_lo/hi
; (uses tmp_a/tmp_b as scratch copies so running sum is preserved)
; ============================================================
compute_offer:
    lda #0
    sta quot_lo
    sta quot_hi

    lda sum_lo
    sta tmp_a
    lda sum_hi
    sta tmp_b

@loop:
    lda tmp_b
    bne @sub
    lda tmp_a
    cmp count8
    bcc @done
@sub:
    lda tmp_a
    sec
    sbc count8
    sta tmp_a
    lda tmp_b
    sbc #0
    sta tmp_b
    inc quot_lo
    bne @loop
    inc quot_hi
    jmp @loop
@done:
    lda quot_lo
    sta offer_lo
    lda quot_hi
    sta offer_hi
    rts

; ============================================================
; bin2dec: converts 16-bit value in (tmp_a=lo, tmp_b=hi)
; fills digit0..digit4 (numeric digit values 0-9, not tile idx)
; ============================================================
bin2dec:
    ldx #0
@d0:
    lda tmp_b
    cmp #>10000
    bcc @d0done
    bne @d0sub
    lda tmp_a
    cmp #<10000
    bcc @d0done
@d0sub:
    lda tmp_a
    sec
    sbc #<10000
    sta tmp_a
    lda tmp_b
    sbc #>10000
    sta tmp_b
    inx
    jmp @d0
@d0done:
    stx digit0

    ldx #0
@d1:
    lda tmp_b
    cmp #>1000
    bcc @d1done
    bne @d1sub
    lda tmp_a
    cmp #<1000
    bcc @d1done
@d1sub:
    lda tmp_a
    sec
    sbc #<1000
    sta tmp_a
    lda tmp_b
    sbc #>1000
    sta tmp_b
    inx
    jmp @d1
@d1done:
    stx digit1

    ldx #0
@d2:
    lda tmp_b
    bne @d2sub
    lda tmp_a
    cmp #100
    bcc @d2done
@d2sub:
    lda tmp_a
    sec
    sbc #100
    sta tmp_a
    lda tmp_b
    sbc #0
    sta tmp_b
    inx
    jmp @d2
@d2done:
    stx digit2

    ldx #0
@d3:
    lda tmp_b
    bne @d3sub
    lda tmp_a
    cmp #10
    bcc @d3done
@d3sub:
    lda tmp_a
    sec
    sbc #10
    sta tmp_a
    lda tmp_b
    sbc #0
    sta tmp_b
    inx
    jmp @d3
@d3done:
    stx digit3

    lda tmp_a
    sta digit4
    rts

; ============================================================
; build_offer_str: formats offer_lo/hi into offer_str buffer
; ("$" + up to 5 digits, leading zeros blanked, terminated $FF)
; ============================================================
build_offer_str:
    lda offer_lo
    sta tmp_a
    lda offer_hi
    sta tmp_b
    jsr bin2dec

    lda #37            ; '$'
    sta offer_str+0

    ldx #1
    lda digit0
    bne @show0
    lda #TILE_SPACE
    sta offer_str,x
    jmp @c1
@show0:
    clc
    adc #27
    sta offer_str,x

@c1:
    ldx #2
    lda digit0
    bne @show1
    lda digit1
    bne @show1
    lda #TILE_SPACE
    sta offer_str,x
    jmp @c2
@show1:
    lda digit1
    clc
    adc #27
    sta offer_str,x

@c2:
    ldx #3
    lda digit0
    bne @show2
    lda digit1
    bne @show2
    lda digit2
    bne @show2
    lda #TILE_SPACE
    sta offer_str,x
    jmp @c3
@show2:
    lda digit2
    clc
    adc #27
    sta offer_str,x

@c3:
    ldx #4
    lda digit0
    bne @show3
    lda digit1
    bne @show3
    lda digit2
    bne @show3
    lda digit3
    bne @show3
    lda #TILE_SPACE
    sta offer_str,x
    jmp @c4
@show3:
    lda digit3
    clc
    adc #27
    sta offer_str,x

@c4:
    lda digit4
    clc
    adc #27
    sta offer_str+5

    lda #$FF
    sta offer_str+6
    rts

; ============================================================
; print_string: prints null($FF)-terminated tile string.
; input: ptr_lo/ptr_hi = string pointer, ppu_hi/ppu_lo = dest addr
; disables rendering during write.
; ============================================================
print_string:
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    ldy #0
@loop:
    lda (ptr_lo),y
    cmp #$FF
    beq @done
    sta $2007
    iny
    jmp @loop
@done:
    jsr restore_scroll
    lda #$1E
    sta $2001
    rts

; ============================================================
; print_string_rc: input A=row, X=col, ptr_lo/ptr_hi already set
; ============================================================
print_string_rc:
    sta tmp_row
    stx tmp_col
    jsr calc_ppu_addr
    jsr print_string
    rts

; ============================================================
; clear_row: clears a full 32-tile row (rendering off)
; input: A = row
; ============================================================
clear_row:
    sta tmp_row
    lda #0
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    ldx #32
    lda #TILE_SPACE
@loop:
    sta $2007
    dex
    bne @loop
    jsr restore_scroll
    lda #$1E
    sta $2001
    rts

clear_message_rows:
    lda #9
    jsr clear_row
    lda #11
    jsr clear_row
    lda #23
    jsr clear_row
    lda #25
    jsr clear_row
    rts

; ============================================================
; clear_all_rows: clears entire visible nametable (rows 0-29)
; ============================================================
clear_all_rows:
    lda #0
    sta loop_i
@loop:
    lda loop_i
    jsr clear_row
    inc loop_i
    lda loop_i
    cmp #30
    bne @loop
    rts

; ============================================================
; draw_title_screen
; ============================================================
draw_title_screen:
    jsr clear_all_rows
    lda #<str_title
    sta ptr_lo
    lda #>str_title
    sta ptr_hi
    lda #3
    ldx #8
    jsr print_string_rc

    lda #<str_subtitle
    sta ptr_lo
    lda #>str_subtitle
    sta ptr_hi
    lda #6
    ldx #10
    jsr print_string_rc

    lda #<str_pressstart
    sta ptr_lo
    lda #>str_pressstart
    sta ptr_hi
    lda #20
    ldx #10
    jsr print_string_rc
    rts

; ============================================================
; draw_game_screen: draws host/contestant blocks + all 10 cases
; ============================================================
draw_game_screen:
    jsr clear_all_rows
    lda #<str_title2
    sta ptr_lo
    lda #>str_title2
    sta ptr_hi
    lda #1
    ldx #7
    jsr print_string_rc

    lda #<str_host
    sta ptr_lo
    lda #>str_host
    sta ptr_hi
    lda #3
    ldx #3
    jsr print_string_rc

    lda #<str_you
    sta ptr_lo
    lda #>str_you
    sta ptr_hi
    lda #3
    ldx #26
    jsr print_string_rc

    ; host block rows 4-6 cols 2-6
    ldx #4
@hrow:
    stx tmp_row
    lda #2
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    ldy #5
    lda #TILE_SOLID
@hcol:
    sta $2007
    dey
    bne @hcol
    jsr restore_scroll
    lda #$1E
    sta $2001
    ldx tmp_row
    inx
    cpx #7
    bne @hrow

    ; contestant block rows 4-6 cols 24-28
    ldx #4
@crow:
    stx tmp_row
    lda #24
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    ldy #5
    lda #TILE_SOLID
@ccol:
    sta $2007
    dey
    bne @ccol
    jsr restore_scroll
    lda #$1E
    sta $2001
    ldx tmp_row
    inx
    cpx #7
    bne @crow

    ; draw all 10 case icons + numbers
    ldx #0
@caseloop:
    stx loop_i
    lda case_row_icon,x
    sta tmp_row
    lda case_col,x
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    lda #TILE_CASE
    sta $2007
    jsr restore_scroll
    lda #$1E
    sta $2001

    ldx loop_i
    lda case_row_num,x
    sta tmp_row
    lda case_col,x
    sta tmp_col
    lda case_num_str_lo,x
    sta ptr_lo
    lda case_num_str_hi,x
    sta ptr_hi
    lda tmp_row
    ldx tmp_col
    jsr print_string_rc

    ldx loop_i
    inx
    cpx #10
    bne @caseloop

    lda #<str_pickown
    sta ptr_lo
    lda #>str_pickown
    sta ptr_hi
    lda #9
    ldx #3
    jsr print_string_rc

    ldx #0
    stx cursor
    lda #$FF
    sta last_cursor
    jsr redraw_cursor
    rts

; ============================================================
; draw_case_value: redraws case at 'cursor' index with its
; dollar value string (case is already marked opened)
; ============================================================
draw_case_value:
    ldx cursor
    lda case_row_icon,x
    sta tmp_row
    lda case_col,x
    sta tmp_col

    lda case_value,x
    tax
    lda val_str_lo,x
    sta ptr_lo
    lda val_str_hi,x
    sta ptr_hi

    lda tmp_row
    ldx tmp_col
    jsr print_string_rc
    rts

; ============================================================
; draw_open_prompt
; ============================================================
draw_open_prompt:
    jsr clear_message_rows
    lda #<str_open1
    sta ptr_lo
    lda #>str_open1
    sta ptr_hi
    lda #9
    ldx #4
    jsr print_string_rc

    lda cases_left
    clc
    adc #27
    sta open_num_buf
    lda #$FF
    sta open_num_buf+1

    lda #<open_num_buf
    sta ptr_lo
    lda #>open_num_buf
    sta ptr_hi
    lda #9
    ldx #24
    jsr print_string_rc
    rts

; ============================================================
; draw_offer_screen
; ============================================================
draw_offer_screen:
    jsr build_offer_str

    lda #9
    jsr clear_row
    lda #11
    jsr clear_row
    lda #23
    jsr clear_row

    lda #<str_offer1
    sta ptr_lo
    lda #>str_offer1
    sta ptr_hi
    lda #9
    ldx #2
    jsr print_string_rc

    lda #<offer_str
    sta ptr_lo
    lda #>offer_str
    sta ptr_hi
    lda #9
    ldx #24
    jsr print_string_rc

    lda #<str_dealprompt
    sta ptr_lo
    lda #>str_dealprompt
    sta ptr_hi
    lda #23
    ldx #4
    jsr print_string_rc
    rts

; ============================================================
; draw_deal_result: sum_lo/hi holds final amount
; ============================================================
draw_deal_result:
    lda sum_lo
    sta offer_lo
    lda sum_hi
    sta offer_hi
    jsr build_offer_str

    lda #9
    jsr clear_row
    lda #11
    jsr clear_row
    lda #23
    jsr clear_row
    lda #25
    jsr clear_row

    lda #<str_deal_taken
    sta ptr_lo
    lda #>str_deal_taken
    sta ptr_hi
    lda #9
    ldx #4
    jsr print_string_rc

    lda #<offer_str
    sta ptr_lo
    lda #>offer_str
    sta ptr_hi
    lda #11
    ldx #12
    jsr print_string_rc

    lda #<str_restart
    sta ptr_lo
    lda #>str_restart
    sta ptr_hi
    lda #25
    ldx #10
    jsr print_string_rc
    rts

; ============================================================
; draw_swap_prompt
; ============================================================
draw_swap_prompt:
    lda #9
    jsr clear_row
    lda #11
    jsr clear_row
    lda #23
    jsr clear_row

    lda #<str_swap1
    sta ptr_lo
    lda #>str_swap1
    sta ptr_hi
    lda #9
    ldx #3
    jsr print_string_rc

    lda #<str_swap2
    sta ptr_lo
    lda #>str_swap2
    sta ptr_hi
    lda #23
    ldx #2
    jsr print_string_rc
    rts

; ============================================================
; draw_final_result: sum_lo/hi holds final case's value
; ============================================================
draw_final_result:
    lda sum_lo
    sta offer_lo
    lda sum_hi
    sta offer_hi
    jsr build_offer_str

    lda #9
    jsr clear_row
    lda #11
    jsr clear_row
    lda #23
    jsr clear_row
    lda #25
    jsr clear_row

    lda #<str_final_result
    sta ptr_lo
    lda #>str_final_result
    sta ptr_hi
    lda #9
    ldx #3
    jsr print_string_rc

    lda #<offer_str
    sta ptr_lo
    lda #>offer_str
    sta ptr_hi
    lda #11
    ldx #12
    jsr print_string_rc

    lda #<str_restart
    sta ptr_lo
    lda #>str_restart
    sta ptr_hi
    lda #25
    ldx #10
    jsr print_string_rc
    rts

; ============================================================
; DATA
; ============================================================
.segment "RODATA"

palette:
    .byte $0F,$30,$0F,$0F
    .byte $0F,$30,$0F,$0F
    .byte $0F,$30,$0F,$0F
    .byte $0F,$30,$0F,$0F
    .byte $0F,$30,$0F,$0F
    .byte $0F,$30,$0F,$0F
    .byte $0F,$30,$0F,$0F
    .byte $0F,$30,$0F,$0F

round_sched: .byte 3,3,2

case_row_icon: .byte 14,14,14,14,14,19,19,19,19,19
case_row_num:  .byte 15,15,15,15,15,20,20,20,20,20
case_row_cur:  .byte 13,13,13,13,13,18,18,18,18,18
case_col:      .byte 1,7,13,19,25,1,7,13,19,25

values_lo: .byte <1,<10,<50,<100,<500,<1000,<2500,<5000,<7500,<10000
values_hi: .byte >1,>10,>50,>100,>500,>1000,>2500,>5000,>7500,>10000

str_title:      .byte "DEAL OR NO DEAL",$FF
str_title2:     .byte "DEAL OR NO DEAL",$FF
str_subtitle:   .byte "NES EDITION",$FF
str_pressstart: .byte "PRESS START",$FF
str_host:       .byte "HOST",$FF
str_you:        .byte "YOU",$FF
str_pickown:    .byte "PICK YOUR CASE - A",$FF
str_open1:      .byte "OPEN CASES LEFT",$FF
str_offer1:     .byte "BANKER OFFERS",$FF
str_dealprompt: .byte "A=DEAL   B=NO DEAL",$FF
str_deal_taken: .byte "YOU TOOK THE DEAL",$FF
str_swap1:      .byte "FINAL CASE REMAINS",$FF
str_swap2:      .byte "A=KEEP CASE  B=SWAP",$FF
str_final_result: .byte "YOUR CASE HELD",$FF
str_restart:    .byte "PRESS START",$FF

val_str_0: .byte "$1",$FF
val_str_1: .byte "$10",$FF
val_str_2: .byte "$50",$FF
val_str_3: .byte "$100",$FF
val_str_4: .byte "$500",$FF
val_str_5: .byte "$1000",$FF
val_str_6: .byte "$2500",$FF
val_str_7: .byte "$5000",$FF
val_str_8: .byte "$7500",$FF
val_str_9: .byte "$10000",$FF

val_str_lo: .byte <val_str_0,<val_str_1,<val_str_2,<val_str_3,<val_str_4,<val_str_5,<val_str_6,<val_str_7,<val_str_8,<val_str_9
val_str_hi: .byte >val_str_0,>val_str_1,>val_str_2,>val_str_3,>val_str_4,>val_str_5,>val_str_6,>val_str_7,>val_str_8,>val_str_9

case_num_1: .byte "1",$FF
case_num_2: .byte "2",$FF
case_num_3: .byte "3",$FF
case_num_4: .byte "4",$FF
case_num_5: .byte "5",$FF
case_num_6: .byte "6",$FF
case_num_7: .byte "7",$FF
case_num_8: .byte "8",$FF
case_num_9: .byte "9",$FF
case_num_10: .byte "10",$FF

case_num_str_lo: .byte <case_num_1,<case_num_2,<case_num_3,<case_num_4,<case_num_5,<case_num_6,<case_num_7,<case_num_8,<case_num_9,<case_num_10
case_num_str_hi: .byte >case_num_1,>case_num_2,>case_num_3,>case_num_4,>case_num_5,>case_num_6,>case_num_7,>case_num_8,>case_num_9,>case_num_10

; ------------------------------------------------------------
.segment "CHARS"
    .incbin "build/game.chr"

; ------------------------------------------------------------
.segment "VECTORS"
    .addr NMI
    .addr RESET
    .addr IRQ
