; ============================================================
; DEAL OR NO DEAL - NES homebrew (22-case edition)
; ============================================================

.segment "HEADER"
    .byte "NES", $1A
    .byte 2        ; 2 * 16KB PRG
    .byte 1        ; 1 * 8KB CHR
    .byte $01      ; mapper 0, vertical mirroring
    .byte $00
    .byte 0,0,0,0,0,0,0,0

; ------------------------------------------------------------
; Custom charmap: map ASCII chars used in string literals to
; our tile indices generated by gen_chr.cjs
; ------------------------------------------------------------
.charmap $20, 0        ; space
.charmap $41, 1  ; A
.charmap $42, 2  ; B
.charmap $43, 3  ; C
.charmap $44, 4  ; D
.charmap $45, 5  ; E
.charmap $46, 6  ; F
.charmap $47, 7  ; G
.charmap $48, 8  ; H
.charmap $49, 9  ; I
.charmap $4A, 10 ; J
.charmap $4B, 11 ; K
.charmap $4C, 12 ; L
.charmap $4D, 13 ; M
.charmap $4E, 14 ; N
.charmap $4F, 15 ; O
.charmap $50, 16 ; P
.charmap $51, 17 ; Q
.charmap $52, 18 ; R
.charmap $53, 19 ; S
.charmap $54, 20 ; T
.charmap $55, 21 ; U
.charmap $56, 22 ; V
.charmap $57, 23 ; W
.charmap $58, 24 ; X
.charmap $59, 25 ; Y
.charmap $5A, 26 ; Z
.charmap $30, 27 ; 0
.charmap $31, 28 ; 1
.charmap $32, 29 ; 2
.charmap $33, 30 ; 3
.charmap $34, 31 ; 4
.charmap $35, 32 ; 5
.charmap $36, 33 ; 6
.charmap $37, 34 ; 7
.charmap $38, 35 ; 8
.charmap $39, 36 ; 9
.charmap $24, 37 ; $
.charmap $2C, 38 ; ,
.charmap $2E, 39 ; .
.charmap $3A, 40 ; :
.charmap $3F, 41 ; ?
.charmap $21, 42 ; !
.charmap $2D, 43 ; -

TILE_SPACE   = 0
TILE_SOLID   = 44
TILE_CASE    = 45
TILE_CURSOR  = 46
TILE_HEAD    = 47
TILE_LEGS    = 48

BTN_A      = $80
BTN_B      = $40
BTN_SELECT = $20
BTN_START  = $10
BTN_UP     = $08
BTN_DOWN   = $04
BTN_LEFT   = $02
BTN_RIGHT  = $01

ST_TITLE      = 0
ST_PICK_OWN   = 1
ST_PICK_OPEN  = 2
ST_OFFER      = 3
ST_FINAL_SWAP = 4
ST_GAMEOVER   = 5

CASES_TOTAL = 22
NUM_ROUNDS  = 6
NUM_COLS    = 11

CUR_ROW_A = 12
ICON_ROW_A = 13
NUM_ROW_A  = 14
CUR_ROW_B  = 16
ICON_ROW_B = 17
NUM_ROW_B  = 18

MSGROW1 = 8
MSGROW2 = 10
PROMPTROW1 = 20
PROMPTROW2 = 22

; ------------------------------------------------------------
; Zero page variables
; ------------------------------------------------------------
.segment "ZEROPAGE"
nmi_flag:       .res 1
frame_counter:  .res 1
pad1:           .res 1
pad1_old:       .res 1
pad1_new:       .res 1
game_state:     .res 1
cursor:         .res 1
last_cursor:    .res 1
own_case:       .res 1
round_idx:      .res 1
cases_left:     .res 1
final_other:    .res 1
chosen_case:    .res 1
rng:            .res 1

ptr_lo:         .res 1
ptr_hi:         .res 1
ppu_lo:         .res 1
ppu_hi:         .res 1
tmp_row:        .res 1
tmp_col:        .res 1
tmp_a:          .res 1
tmp_b:          .res 1
loop_i:         .res 1
loop_j:         .res 1

sum_lo:         .res 1
sum_hi:         .res 1
count8:         .res 1
quot_lo:        .res 1
quot_hi:        .res 1
digit0:         .res 1
digit1:         .res 1
digit2:         .res 1
digit3:         .res 1
digit4:         .res 1

sq2_timer:      .res 1
noise_timer:    .res 1
music_step:     .res 1
mus_timer:      .res 1
anim_count:     .res 1
blink_state:    .res 1

; ------------------------------------------------------------
; RAM arrays
; ------------------------------------------------------------
.segment "BSS"
case_value:     .res 22   ; value-index (0-21) assigned to each case slot
case_opened:    .res 22   ; 0/1
offer_lo:       .res 1
offer_hi:       .res 1
offer_str:      .res 8    ; '$' + up to 5 digits + terminator
open_num_buf:   .res 3

; ------------------------------------------------------------
.segment "CODE"

RESET:
    sei
    cld
    ldx #$40
    stx $4017
    ldx #$FF
    txs
    inx             ; X = 0
    stx $2000
    stx $2001
    stx $4010

vblankwait1:
    bit $2002
    bpl vblankwait1

    ; clear RAM
clear_ram:
    lda #0
    sta $0000,x
    sta $0100,x
    sta $0300,x
    sta $0400,x
    sta $0500,x
    sta $0600,x
    sta $0700,x
    lda #$FE
    sta $0200,x     ; sprite ram (unused, park off-screen)
    inx
    bne clear_ram

vblankwait2:
    bit $2002
    bpl vblankwait2

    ; load palette
    lda $2002
    lda #$3F
    sta $2006
    lda #$00
    sta $2006
    ldx #0
load_pal:
    lda palette,x
    sta $2007
    inx
    cpx #32
    bne load_pal

    ; clear nametable 0 + attribute table to 0
    lda $2002
    lda #$20
    sta $2006
    lda #$00
    sta $2006
    lda #0
    ldx #4          ; 4 pages of 256 = 1024 bytes
clear_nt_page:
    ldy #0
clear_nt_byte:
    sta $2007
    iny
    bne clear_nt_byte
    dex
    bne clear_nt_page

    lda #1
    sta rng

    ; APU init: enable square1/square2/triangle/noise, set up music channel
    lda #$0F
    sta $4015
    lda #$34        ; duty00, halt-length/loop-envelope, constant vol, vol=4
    sta $4000
    lda #0
    sta music_step
    sta mus_timer
    sta sq2_timer
    sta noise_timer

    lda #$88
    sta $2000       ; NMI on, bg pattern table 0, sprites table 0
    lda #$00
    sta $2001       ; rendering off for now

    lda #ST_TITLE
    sta game_state
    lda #0
    sta blink_state
    jsr draw_title_screen

    jsr restore_scroll
    lda #$1E
    sta $2001       ; enable bg + sprites rendering (leftmost col too)

main_loop:
    jsr wait_vblank
    jsr read_pads
    jsr update_music
    jsr update_sfx
    jsr do_state
    jmp main_loop

; ------------------------------------------------------------
NMI:
    pha
    txa
    pha
    tya
    pha

    inc nmi_flag
    inc frame_counter

    pla
    tay
    pla
    tax
    pla
    rti

IRQ:
    rti

; ------------------------------------------------------------
wait_vblank:
    lda nmi_flag
@loop:
    cmp nmi_flag
    beq @loop
    rts

; ------------------------------------------------------------
read_pads:
    lda pad1
    sta pad1_old

    lda #1
    sta $4016
    lda #0
    sta $4016

    ldx #8
    lda #0
    sta tmp_a
@loop:
    lda $4016
    lsr a
    rol tmp_a
    dex
    bne @loop
    lda tmp_a
    sta pad1

    lda pad1
    eor pad1_old
    and pad1
    sta pad1_new
    rts

; ------------------------------------------------------------
; update_music: advances the background "tense" bassline loop
; ------------------------------------------------------------
update_music:
    inc mus_timer
    lda mus_timer
    cmp #24
    bcc @done
    lda #0
    sta mus_timer
    inc music_step
    lda music_step
    cmp #4
    bcc @gotstep
    lda #0
    sta music_step
@gotstep:
    ldx music_step
    lda music_period_lo,x
    sta $4002
    lda music_period_hi,x
    sta $4003
@done:
    rts

; ------------------------------------------------------------
; update_sfx: counts down square2/noise SFX timers and mutes
; the channel when a timer reaches zero
; ------------------------------------------------------------
update_sfx:
    lda sq2_timer
    beq @skipsq2
    dec sq2_timer
    bne @skipsq2
    lda #$30
    sta $4004
@skipsq2:
    lda noise_timer
    beq @skipnoise
    dec noise_timer
    bne @skipnoise
    lda #$30
    sta $400C
@skipnoise:
    rts

; ------------------------------------------------------------
; play_beep: A=period_lo, X=period_hi, Y=frames (volume fixed via caller)
; uses tmp_b as volume passed by caller before call (see wrapper sfx_*)
; ------------------------------------------------------------
sfx_move:
    lda #$38        ; vol 8
    sta $4004
    lda #$F0
    sta $4006
    lda #$00
    sta $4007
    lda #4
    sta sq2_timer
    rts

sfx_confirm:
    lda #$3A        ; vol 10
    sta $4004
    lda #$80
    sta $4006
    lda #$00
    sta $4007
    lda #6
    sta sq2_timer
    rts

sfx_deal:
    lda #$3C        ; vol 12
    sta $4004
    lda #$60
    sta $4006
    lda #$00
    sta $4007
    lda #14
    sta sq2_timer
    rts

sfx_nodeal:
    lda #$3A        ; vol 10
    sta $4004
    lda #$80
    sta $4006
    lda #$01
    sta $4007
    lda #10
    sta sq2_timer
    rts

sfx_open:
    lda #$3C        ; vol 12
    sta $400C
    lda #$08
    sta $400E
    lda #$00
    sta $400F
    lda #10
    sta noise_timer
    rts

; ------------------------------------------------------------
do_state:
    lda game_state
    cmp #ST_TITLE
    bne @s1
    jmp state_title
@s1:
    cmp #ST_PICK_OWN
    bne @s2
    jmp state_pick_own
@s2:
    cmp #ST_PICK_OPEN
    bne @s3
    jmp state_pick_open
@s3:
    cmp #ST_OFFER
    bne @s4
    jmp state_offer
@s4:
    cmp #ST_FINAL_SWAP
    bne @s5
    jmp state_final_swap
@s5:
    jmp state_gameover

; ============================================================
; STATE: TITLE (with blinking "press start")
; ============================================================
state_title:
    lda frame_counter
    and #$20
    beq @wantblank
    lda #1
    jmp @gotwant
@wantblank:
    lda #0
@gotwant:
    cmp blink_state
    beq @noblink
    sta blink_state
    cmp #0
    beq @clearit
    lda #<str_pressstart
    sta ptr_lo
    lda #>str_pressstart
    sta ptr_hi
    lda #20
    ldx #10
    jsr print_string_rc
    jmp @noblink
@clearit:
    lda #20
    jsr clear_row
@noblink:
    lda pad1_new
    and #BTN_START
    beq @done
    jsr sfx_confirm
    jsr init_game
@done:
    rts

; ============================================================
; STATE: PICK OWN CASE
; ============================================================
state_pick_own:
    jsr handle_cursor_move

    lda pad1_new
    and #BTN_A
    beq @done

    jsr sfx_confirm

    lda cursor
    sta own_case

    lda #ST_PICK_OPEN
    sta game_state
    lda #0
    sta round_idx
    lda round_sched
    sta cases_left

    jsr move_cursor_to_valid
    jsr draw_open_prompt
@done:
    rts

; ============================================================
; STATE: PICK CASES TO OPEN
; ============================================================
state_pick_open:
    jsr handle_cursor_move

    lda pad1_new
    and #BTN_A
    beq @done

    ; validate: not own_case, not already opened
    lda cursor
    cmp own_case
    beq @done
    ldx cursor
    lda case_opened,x
    bne @done

    ; open it
    lda #1
    sta case_opened,x

    jsr case_open_animation
    jsr draw_case_value

    ; subtract its value from remaining sum, decrement count
    ldx cursor
    lda case_value,x
    tax
    lda sum_lo
    sec
    sbc values_lo,x
    sta sum_lo
    lda sum_hi
    sbc values_hi,x
    sta sum_hi
    dec count8

    dec cases_left
    lda cases_left
    bne @continue_round

    ; round finished - compute offer
    jsr compute_offer
    lda #ST_OFFER
    sta game_state
    jsr draw_offer_screen
    rts

@continue_round:
    jsr draw_open_prompt
@done:
    rts

; ============================================================
; STATE: OFFER (deal or no deal)
; ============================================================
state_offer:
    lda pad1_new
    and #BTN_A
    beq @check_b
    ; DEAL - take the offer
    jsr sfx_deal
    lda offer_lo
    sta sum_lo         ; reuse sum as "final winnings" holder for reveal
    lda offer_hi
    sta sum_hi
    jsr draw_deal_result
    lda #ST_GAMEOVER
    sta game_state
    rts

@check_b:
    lda pad1_new
    and #BTN_B
    beq @done

    jsr sfx_nodeal

    inc round_idx
    lda round_idx
    cmp #NUM_ROUNDS
    bcc @next_round

    ; all main rounds done -> find final_other_case, go to swap stage
    jsr find_final_other
    lda #ST_FINAL_SWAP
    sta game_state
    jsr draw_swap_prompt
    rts

@next_round:
    ldx round_idx
    lda round_sched,x
    sta cases_left
    lda #ST_PICK_OPEN
    sta game_state
    jsr move_cursor_to_valid
    jsr draw_open_prompt
@done:
    rts

; ============================================================
; STATE: FINAL SWAP DECISION
; ============================================================
state_final_swap:
    lda pad1_new
    and #BTN_A
    beq @check_b
    jsr sfx_confirm
    lda own_case
    sta chosen_case
    jmp @reveal
@check_b:
    lda pad1_new
    and #BTN_B
    beq @done
    jsr sfx_confirm
    lda final_other
    sta chosen_case
@reveal:
    ldx chosen_case
    lda case_value,x
    tax
    lda values_lo,x
    sta sum_lo
    lda values_hi,x
    sta sum_hi
    jsr draw_final_result
    lda #ST_GAMEOVER
    sta game_state
@done:
    rts

; ============================================================
; STATE: GAME OVER (wait for start to restart)
; ============================================================
state_gameover:
    lda pad1_new
    and #BTN_START
    beq @done
    lda #$00
    sta $2001
    jsr clear_message_rows
    lda #ST_TITLE
    sta game_state
    lda #0
    sta blink_state
    jsr draw_title_screen
    jsr restore_scroll
    lda #$1E
    sta $2001
@done:
    rts

; ============================================================
; find_final_other: scans case_opened[] for the one case that
; is not opened and not own_case
; ============================================================
find_final_other:
    ldx #0
@loop:
    cpx own_case
    beq @skip
    lda case_opened,x
    bne @skip
    stx final_other
    rts
@skip:
    inx
    cpx #CASES_TOTAL
    bne @loop
    rts

; ============================================================
; move_cursor_to_valid: move cursor to the next unopened,
; non-own case (search forward, wrap)
; ============================================================
move_cursor_to_valid:
    ldx #0
@loop:
    cpx own_case
    beq @skip
    lda case_opened,x
    bne @skip
    stx cursor
    jsr redraw_cursor
    rts
@skip:
    inx
    cpx #CASES_TOTAL
    bne @loop
    rts

; ============================================================
; handle_cursor_move: reads pad1_new for dpad, updates cursor
; grid is 2 rows x 11 cols
; ============================================================
handle_cursor_move:
    lda cursor
    cmp #NUM_COLS
    bcc @rowIs0
    sec
    sbc #NUM_COLS
    sta tmp_col
    lda #1
    sta tmp_row
    jmp @gotrowcol
@rowIs0:
    sta tmp_col
    lda #0
    sta tmp_row
@gotrowcol:

    lda pad1_new
    and #BTN_RIGHT
    beq @tryleft
    inc tmp_col
    lda tmp_col
    cmp #NUM_COLS
    bne @recalc
    lda #0
    sta tmp_col
    jmp @recalc

@tryleft:
    lda pad1_new
    and #BTN_LEFT
    beq @tryud
    lda tmp_col
    bne @decok
    lda #NUM_COLS
@decok:
    sec
    sbc #1
    sta tmp_col
    jmp @recalc

@tryud:
    lda pad1_new
    and #(BTN_UP | BTN_DOWN)
    beq @none
    lda tmp_row
    eor #1
    sta tmp_row
    jmp @recalc

@none:
    rts

@recalc:
    lda tmp_row
    beq @rowzero
    lda tmp_col
    clc
    adc #NUM_COLS
    sta cursor
    jmp @recalcdone
@rowzero:
    lda tmp_col
    sta cursor
@recalcdone:
    jsr redraw_cursor
    jsr sfx_move
    rts

; ============================================================
; redraw_cursor: clears old cursor tile, draws new one
; ============================================================
redraw_cursor:
    lda last_cursor
    cmp #$FF
    beq @drawnew
    tax
    lda case_row_cur,x
    sta tmp_row
    lda case_col,x
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    lda #TILE_SPACE
    sta $2007
    jsr restore_scroll
    lda #$1E
    sta $2001

@drawnew:
    ldx cursor
    lda case_row_cur,x
    sta tmp_row
    lda case_col,x
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    lda #TILE_CURSOR
    sta $2007
    jsr restore_scroll
    lda #$1E
    sta $2001

    lda cursor
    sta last_cursor
    rts

; ============================================================
; calc_ppu_addr: input tmp_row, tmp_col -> ppu_hi/ppu_lo
; addr = $2000 + row*32 + col
; ============================================================
calc_ppu_addr:
    lda tmp_row
    sta tmp_a
    lda #0
    sta tmp_b
    ldx #5
@shift:
    asl tmp_a
    rol tmp_b
    dex
    bne @shift
    lda tmp_a
    clc
    adc tmp_col
    sta ppu_lo
    lda tmp_b
    adc #$20
    sta ppu_hi
    rts

; ============================================================
; case_open_animation: brief flicker of the case tile before
; its value is revealed, with an "opening" noise burst.
; ============================================================
case_open_animation:
    jsr sfx_open
    lda #4
    sta anim_count
@loop:
    ldx cursor
    lda case_row_icon,x
    sta tmp_row
    lda case_col,x
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    lda #TILE_SPACE
    sta $2007
    jsr restore_scroll
    lda #$1E
    sta $2001
    jsr wait_vblank
    jsr wait_vblank

    ldx cursor
    lda case_row_icon,x
    sta tmp_row
    lda case_col,x
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    lda #TILE_CASE
    sta $2007
    jsr restore_scroll
    lda #$1E
    sta $2001
    jsr wait_vblank
    jsr wait_vblank

    dec anim_count
    bne @loop
    rts

; ============================================================
; init_game: shuffle cases, reset state, draw game screen
; ============================================================
init_game:
    lda #$00
    sta $2001

    ; seed rng using frame_counter (never zero)
    lda frame_counter
    ora #1
    sta rng

    ; identity fill
    ldx #0
@fill:
    txa
    sta case_value,x
    lda #0
    sta case_opened,x
    inx
    cpx #CASES_TOTAL
    bne @fill

    ; fisher-yates shuffle: for i = 21 downto 1, j = rand(0..i)
    ldx #21
@shuffle:
    stx loop_i
    inx                  ; range = i+1
    txa
    jsr rand_range        ; returns A = rand in [0, range)
    sta loop_j

    ldx loop_i
    lda case_value,x
    sta tmp_a
    ldy loop_j
    lda case_value,y
    sta case_value,x
    lda tmp_a
    sta case_value,y

    ldx loop_i
    dex
    cpx #0
    beq @doneshuffle
    jmp @shuffle
@doneshuffle:

    lda #$FF
    sta own_case
    sta last_cursor
    lda #0
    sta cursor
    sta round_idx

    lda #<23666
    sta sum_lo
    lda #>23666
    sta sum_hi
    lda #CASES_TOTAL
    sta count8

    lda #ST_PICK_OWN
    sta game_state

    jsr draw_game_screen
    jsr restore_scroll
    lda #$1E
    sta $2001
    rts

; ============================================================
; rand_range: input A = range (1..22), output A = rand in [0,range)
; updates rng (8-bit LFSR)
; ============================================================
rand_range:
    sta tmp_b            ; save range
    lda rng
    lsr a
    bcc @noeor
    eor #$B4
@noeor:
    sta rng
@modloop:
    cmp tmp_b
    bcc @done
    sbc tmp_b
    jmp @modloop
@done:
    rts

; ============================================================
; compute_offer: sum_lo/hi divided by count8 -> offer_lo/hi
; (uses tmp_a/tmp_b as scratch copies so running sum is preserved)
; ============================================================
compute_offer:
    lda #0
    sta quot_lo
    sta quot_hi

    lda sum_lo
    sta tmp_a
    lda sum_hi
    sta tmp_b

@loop:
    lda tmp_b
    bne @sub
    lda tmp_a
    cmp count8
    bcc @done
@sub:
    lda tmp_a
    sec
    sbc count8
    sta tmp_a
    lda tmp_b
    sbc #0
    sta tmp_b
    inc quot_lo
    bne @loop
    inc quot_hi
    jmp @loop
@done:
    lda quot_lo
    sta offer_lo
    lda quot_hi
    sta offer_hi
    rts

; ============================================================
; bin2dec: converts 16-bit value in (tmp_a=lo, tmp_b=hi)
; fills digit0..digit4 (numeric digit values 0-9, not tile idx)
; ============================================================
bin2dec:
    ldx #0
@d0:
    lda tmp_b
    cmp #>10000
    bcc @d0done
    bne @d0sub
    lda tmp_a
    cmp #<10000
    bcc @d0done
@d0sub:
    lda tmp_a
    sec
    sbc #<10000
    sta tmp_a
    lda tmp_b
    sbc #>10000
    sta tmp_b
    inx
    jmp @d0
@d0done:
    stx digit0

    ldx #0
@d1:
    lda tmp_b
    cmp #>1000
    bcc @d1done
    bne @d1sub
    lda tmp_a
    cmp #<1000
    bcc @d1done
@d1sub:
    lda tmp_a
    sec
    sbc #<1000
    sta tmp_a
    lda tmp_b
    sbc #>1000
    sta tmp_b
    inx
    jmp @d1
@d1done:
    stx digit1

    ldx #0
@d2:
    lda tmp_b
    bne @d2sub
    lda tmp_a
    cmp #100
    bcc @d2done
@d2sub:
    lda tmp_a
    sec
    sbc #100
    sta tmp_a
    lda tmp_b
    sbc #0
    sta tmp_b
    inx
    jmp @d2
@d2done:
    stx digit2

    ldx #0
@d3:
    lda tmp_b
    bne @d3sub
    lda tmp_a
    cmp #10
    bcc @d3done
@d3sub:
    lda tmp_a
    sec
    sbc #10
    sta tmp_a
    lda tmp_b
    sbc #0
    sta tmp_b
    inx
    jmp @d3
@d3done:
    stx digit3

    lda tmp_a
    sta digit4
    rts

; ============================================================
; build_offer_str: formats offer_lo/hi into offer_str buffer
; ("$" + up to 5 digits, leading zeros blanked, terminated $FF)
; ============================================================
build_offer_str:
    lda offer_lo
    sta tmp_a
    lda offer_hi
    sta tmp_b
    jsr bin2dec

    lda #37            ; '$'
    sta offer_str+0

    ldx #1
    lda digit0
    bne @show0
    lda #TILE_SPACE
    sta offer_str,x
    jmp @c1
@show0:
    clc
    adc #27
    sta offer_str,x

@c1:
    ldx #2
    lda digit0
    bne @show1
    lda digit1
    bne @show1
    lda #TILE_SPACE
    sta offer_str,x
    jmp @c2
@show1:
    lda digit1
    clc
    adc #27
    sta offer_str,x

@c2:
    ldx #3
    lda digit0
    bne @show2
    lda digit1
    bne @show2
    lda digit2
    bne @show2
    lda #TILE_SPACE
    sta offer_str,x
    jmp @c3
@show2:
    lda digit2
    clc
    adc #27
    sta offer_str,x

@c3:
    ldx #4
    lda digit0
    bne @show3
    lda digit1
    bne @show3
    lda digit2
    bne @show3
    lda digit3
    bne @show3
    lda #TILE_SPACE
    sta offer_str,x
    jmp @c4
@show3:
    lda digit3
    clc
    adc #27
    sta offer_str,x

@c4:
    lda digit4
    clc
    adc #27
    sta offer_str+5

    lda #$FF
    sta offer_str+6
    rts

; ============================================================
; print_string: prints null($FF)-terminated tile string.
; input: ptr_lo/ptr_hi = string pointer, ppu_hi/ppu_lo = dest addr
; disables rendering during write.
; ============================================================
print_string:
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    ldy #0
@loop:
    lda (ptr_lo),y
    cmp #$FF
    beq @done
    sta $2007
    iny
    jmp @loop
@done:
    jsr restore_scroll
    lda #$1E
    sta $2001
    rts

; ============================================================
; print_string_rc: input A=row, X=col, ptr_lo/ptr_hi already set
; ============================================================
print_string_rc:
    sta tmp_row
    stx tmp_col
    jsr calc_ppu_addr
    jsr print_string
    rts

; ============================================================
; clear_row: clears a full 32-tile row (rendering off)
; input: A = row
; ============================================================
clear_row:
    sta tmp_row
    lda #0
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    ldx #32
    lda #TILE_SPACE
@loop:
    sta $2007
    dex
    bne @loop
    jsr restore_scroll
    lda #$1E
    sta $2001
    rts

; ------------------------------------------------------------
; restore_scroll: resets the PPU address latch and scroll regs
; to (0,0). Must be called before re-enabling rendering any time
; $2006/$2007 were used, since they share internal PPU registers
; with the scroll position.
; ------------------------------------------------------------
restore_scroll:
    lda $2002
    lda #0
    sta $2005
    sta $2005
    rts

clear_message_rows:
    lda #MSGROW1
    jsr clear_row
    lda #MSGROW2
    jsr clear_row
    lda #PROMPTROW1
    jsr clear_row
    lda #PROMPTROW2
    jsr clear_row
    rts

; ============================================================
; clear_all_rows: clears entire visible nametable (rows 0-29)
; ============================================================
clear_all_rows:
    lda #0
    sta loop_i
@loop:
    lda loop_i
    jsr clear_row
    inc loop_i
    lda loop_i
    cmp #30
    bne @loop
    rts

; ============================================================
; draw_title_screen
; ============================================================
draw_title_screen:
    jsr clear_all_rows
    lda #<str_title
    sta ptr_lo
    lda #>str_title
    sta ptr_hi
    lda #3
    ldx #8
    jsr print_string_rc

    lda #<str_subtitle
    sta ptr_lo
    lda #>str_subtitle
    sta ptr_hi
    lda #6
    ldx #10
    jsr print_string_rc

    lda #<str_pressstart
    sta ptr_lo
    lda #>str_pressstart
    sta ptr_hi
    lda #20
    ldx #10
    jsr print_string_rc
    rts

; ============================================================
; draw_game_screen: draws host/contestant figures + all 22 cases
; ============================================================
draw_game_screen:
    jsr clear_all_rows
    lda #<str_title2
    sta ptr_lo
    lda #>str_title2
    sta ptr_hi
    lda #1
    ldx #7
    jsr print_string_rc

    lda #<str_host
    sta ptr_lo
    lda #>str_host
    sta ptr_hi
    lda #3
    ldx #2
    jsr print_string_rc

    lda #<str_you
    sta ptr_lo
    lda #>str_you
    sta ptr_hi
    lda #3
    ldx #25
    jsr print_string_rc

    ; host figure: cols 2-4, row4=head(center col3),row5=body,row6=legs
    lda #4
    sta tmp_row
    lda #3
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    lda #TILE_HEAD
    sta $2007
    jsr restore_scroll
    lda #$1E
    sta $2001

    lda #5
    sta tmp_row
    lda #2
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    ldy #3
    lda #TILE_SOLID
@hbody:
    sta $2007
    dey
    bne @hbody
    jsr restore_scroll
    lda #$1E
    sta $2001

    lda #6
    sta tmp_row
    lda #2
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    ldy #3
    lda #TILE_LEGS
@hlegs:
    sta $2007
    dey
    bne @hlegs
    jsr restore_scroll
    lda #$1E
    sta $2001

    ; contestant figure: cols 25-27
    lda #4
    sta tmp_row
    lda #26
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    lda #TILE_HEAD
    sta $2007
    jsr restore_scroll
    lda #$1E
    sta $2001

    lda #5
    sta tmp_row
    lda #25
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    ldy #3
    lda #TILE_SOLID
@cbody:
    sta $2007
    dey
    bne @cbody
    jsr restore_scroll
    lda #$1E
    sta $2001

    lda #6
    sta tmp_row
    lda #25
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    ldy #3
    lda #TILE_LEGS
@clegs:
    sta $2007
    dey
    bne @clegs
    jsr restore_scroll
    lda #$1E
    sta $2001

    ; draw all 22 case icons + numbers
    ldx #0
@caseloop:
    stx loop_i
    lda case_row_icon,x
    sta tmp_row
    lda case_col,x
    sta tmp_col
    jsr calc_ppu_addr
    lda #$00
    sta $2001
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    lda #TILE_CASE
    sta $2007
    jsr restore_scroll
    lda #$1E
    sta $2001

    ldx loop_i
    lda case_row_num,x
    sta tmp_row
    lda case_col,x
    sta tmp_col
    lda case_num_str_lo,x
    sta ptr_lo
    lda case_num_str_hi,x
    sta ptr_hi
    lda tmp_row
    ldx tmp_col
    jsr print_string_rc

    ldx loop_i
    inx
    cpx #CASES_TOTAL
    bne @caseloop

    lda #<str_pickown
    sta ptr_lo
    lda #>str_pickown
    sta ptr_hi
    lda #MSGROW1
    ldx #3
    jsr print_string_rc

    ldx #0
    stx cursor
    lda #$FF
    sta last_cursor
    jsr redraw_cursor
    rts

; ============================================================
; draw_case_value: redraws case at 'cursor' index with its
; dollar value string (case is already marked opened)
; ============================================================
draw_case_value:
    ldx cursor
    lda case_row_icon,x
    sta tmp_row
    lda case_col,x
    sta tmp_col

    lda case_value,x
    tax
    lda val_str_lo,x
    sta ptr_lo
    lda val_str_hi,x
    sta ptr_hi

    lda tmp_row
    ldx tmp_col
    jsr print_string_rc
    rts

; ============================================================
; draw_open_prompt
; ============================================================
draw_open_prompt:
    lda #MSGROW1
    jsr clear_row
    lda #<str_open1
    sta ptr_lo
    lda #>str_open1
    sta ptr_hi
    lda #MSGROW1
    ldx #4
    jsr print_string_rc

    lda cases_left
    cmp #10
    bcc @onedigit
    ; two-digit (10..22 opens-left never exceeds 21, but be safe)
    lda cases_left
    ldx #0
@tens:
    cmp #10
    bcc @gottens
    sec
    sbc #10
    inx
    jmp @tens
@gottens:
    sta tmp_a
    txa
    clc
    adc #27
    sta open_num_buf
    lda tmp_a
    clc
    adc #27
    sta open_num_buf+1
    lda #$FF
    sta open_num_buf+2
    jmp @gotbuf
@onedigit:
    clc
    adc #27
    sta open_num_buf
    lda #$FF
    sta open_num_buf+1
@gotbuf:
    lda #<open_num_buf
    sta ptr_lo
    lda #>open_num_buf
    sta ptr_hi
    lda #MSGROW1
    ldx #24
    jsr print_string_rc
    rts

; ============================================================
; draw_offer_screen
; ============================================================
draw_offer_screen:
    jsr build_offer_str

    lda #MSGROW1
    jsr clear_row
    lda #MSGROW2
    jsr clear_row
    lda #PROMPTROW1
    jsr clear_row

    lda #<str_offer1
    sta ptr_lo
    lda #>str_offer1
    sta ptr_hi
    lda #MSGROW1
    ldx #2
    jsr print_string_rc

    lda #<offer_str
    sta ptr_lo
    lda #>offer_str
    sta ptr_hi
    lda #MSGROW1
    ldx #24
    jsr print_string_rc

    lda #<str_dealprompt
    sta ptr_lo
    lda #>str_dealprompt
    sta ptr_hi
    lda #PROMPTROW1
    ldx #4
    jsr print_string_rc
    rts

; ============================================================
; draw_deal_result: sum_lo/hi holds final amount
; ============================================================
draw_deal_result:
    lda sum_lo
    sta offer_lo
    lda sum_hi
    sta offer_hi
    jsr build_offer_str

    jsr clear_message_rows

    lda #<str_deal_taken
    sta ptr_lo
    lda #>str_deal_taken
    sta ptr_hi
    lda #MSGROW1
    ldx #4
    jsr print_string_rc

    lda #<offer_str
    sta ptr_lo
    lda #>offer_str
    sta ptr_hi
    lda #MSGROW2
    ldx #12
    jsr print_string_rc

    lda #<str_restart
    sta ptr_lo
    lda #>str_restart
    sta ptr_hi
    lda #PROMPTROW2
    ldx #10
    jsr print_string_rc
    rts

; ============================================================
; draw_swap_prompt
; ============================================================
draw_swap_prompt:
    lda #MSGROW1
    jsr clear_row
    lda #MSGROW2
    jsr clear_row
    lda #PROMPTROW1
    jsr clear_row

    lda #<str_swap1
    sta ptr_lo
    lda #>str_swap1
    sta ptr_hi
    lda #MSGROW1
    ldx #3
    jsr print_string_rc

    lda #<str_swap2
    sta ptr_lo
    lda #>str_swap2
    sta ptr_hi
    lda #PROMPTROW1
    ldx #2
    jsr print_string_rc
    rts

; ============================================================
; draw_final_result: sum_lo/hi holds final case's value
; ============================================================
draw_final_result:
    lda sum_lo
    sta offer_lo
    lda sum_hi
    sta offer_hi
    jsr build_offer_str

    jsr clear_message_rows

    lda #<str_final_result
    sta ptr_lo
    lda #>str_final_result
    sta ptr_hi
    lda #MSGROW1
    ldx #3
    jsr print_string_rc

    lda #<offer_str
    sta ptr_lo
    lda #>offer_str
    sta ptr_hi
    lda #MSGROW2
    ldx #12
    jsr print_string_rc

    lda #<str_restart
    sta ptr_lo
    lda #>str_restart
    sta ptr_hi
    lda #PROMPTROW2
    ldx #10
    jsr print_string_rc
    rts

; ============================================================
; DATA
; ============================================================
.segment "RODATA"

palette:
    .byte $0F,$30,$0F,$0F
    .byte $0F,$30,$0F,$0F
    .byte $0F,$30,$0F,$0F
    .byte $0F,$30,$0F,$0F
    .byte $0F,$30,$0F,$0F
    .byte $0F,$30,$0F,$0F
    .byte $0F,$30,$0F,$0F
    .byte $0F,$30,$0F,$0F

; slow tense 4-step bassline (periods for square1)
music_period_lo: .byte $C9,$EA,$C9,$A0
music_period_hi: .byte $00,$00,$00,$00

round_sched: .byte 5,5,4,3,2,1

case_col: .byte 0,3,6,9,12,15,18,21,24,27,30, 0,3,6,9,12,15,18,21,24,27,30
case_row_icon: .byte ICON_ROW_A,ICON_ROW_A,ICON_ROW_A,ICON_ROW_A,ICON_ROW_A,ICON_ROW_A,ICON_ROW_A,ICON_ROW_A,ICON_ROW_A,ICON_ROW_A,ICON_ROW_A, ICON_ROW_B,ICON_ROW_B,ICON_ROW_B,ICON_ROW_B,ICON_ROW_B,ICON_ROW_B,ICON_ROW_B,ICON_ROW_B,ICON_ROW_B,ICON_ROW_B,ICON_ROW_B
case_row_num:  .byte NUM_ROW_A,NUM_ROW_A,NUM_ROW_A,NUM_ROW_A,NUM_ROW_A,NUM_ROW_A,NUM_ROW_A,NUM_ROW_A,NUM_ROW_A,NUM_ROW_A,NUM_ROW_A, NUM_ROW_B,NUM_ROW_B,NUM_ROW_B,NUM_ROW_B,NUM_ROW_B,NUM_ROW_B,NUM_ROW_B,NUM_ROW_B,NUM_ROW_B,NUM_ROW_B,NUM_ROW_B
case_row_cur:  .byte CUR_ROW_A,CUR_ROW_A,CUR_ROW_A,CUR_ROW_A,CUR_ROW_A,CUR_ROW_A,CUR_ROW_A,CUR_ROW_A,CUR_ROW_A,CUR_ROW_A,CUR_ROW_A, CUR_ROW_B,CUR_ROW_B,CUR_ROW_B,CUR_ROW_B,CUR_ROW_B,CUR_ROW_B,CUR_ROW_B,CUR_ROW_B,CUR_ROW_B,CUR_ROW_B,CUR_ROW_B

values_lo: .byte <1,<5,<10,<25,<50,<75,<100,<200,<300,<400,<500,<600,<700,<800,<900,<1000,<1500,<2000,<2500,<3000,<4000,<5000
values_hi: .byte >1,>5,>10,>25,>50,>75,>100,>200,>300,>400,>500,>600,>700,>800,>900,>1000,>1500,>2000,>2500,>3000,>4000,>5000

str_title:      .byte "DEAL OR NO DEAL",$FF
str_title2:     .byte "DEAL OR NO DEAL",$FF
str_subtitle:   .byte "NES EDITION",$FF
str_pressstart: .byte "PRESS START",$FF
str_host:       .byte "HOST",$FF
str_you:        .byte "YOU",$FF
str_pickown:    .byte "PICK YOUR CASE - A",$FF
str_open1:      .byte "OPEN CASES LEFT",$FF
str_offer1:     .byte "BANKER OFFERS",$FF
str_dealprompt: .byte "A=DEAL   B=NO DEAL",$FF
str_deal_taken: .byte "YOU TOOK THE DEAL",$FF
str_swap1:      .byte "FINAL CASE REMAINS",$FF
str_swap2:      .byte "A=KEEP CASE  B=SWAP",$FF
str_final_result: .byte "YOUR CASE HELD",$FF
str_restart:    .byte "PRESS START",$FF

val_str_0: .byte "$1",$FF
val_str_1: .byte "$5",$FF
val_str_2: .byte "$10",$FF
val_str_3: .byte "$25",$FF
val_str_4: .byte "$50",$FF
val_str_5: .byte "$75",$FF
val_str_6: .byte "$100",$FF
val_str_7: .byte "$200",$FF
val_str_8: .byte "$300",$FF
val_str_9: .byte "$400",$FF
val_str_10: .byte "$500",$FF
val_str_11: .byte "$600",$FF
val_str_12: .byte "$700",$FF
val_str_13: .byte "$800",$FF
val_str_14: .byte "$900",$FF
val_str_15: .byte "$1000",$FF
val_str_16: .byte "$1500",$FF
val_str_17: .byte "$2000",$FF
val_str_18: .byte "$2500",$FF
val_str_19: .byte "$3000",$FF
val_str_20: .byte "$4000",$FF
val_str_21: .byte "$5000",$FF

val_str_lo: .byte <val_str_0,<val_str_1,<val_str_2,<val_str_3,<val_str_4,<val_str_5,<val_str_6,<val_str_7,<val_str_8,<val_str_9,<val_str_10,<val_str_11,<val_str_12,<val_str_13,<val_str_14,<val_str_15,<val_str_16,<val_str_17,<val_str_18,<val_str_19,<val_str_20,<val_str_21
val_str_hi: .byte >val_str_0,>val_str_1,>val_str_2,>val_str_3,>val_str_4,>val_str_5,>val_str_6,>val_str_7,>val_str_8,>val_str_9,>val_str_10,>val_str_11,>val_str_12,>val_str_13,>val_str_14,>val_str_15,>val_str_16,>val_str_17,>val_str_18,>val_str_19,>val_str_20,>val_str_21

case_num_1: .byte "1",$FF
case_num_2: .byte "2",$FF
case_num_3: .byte "3",$FF
case_num_4: .byte "4",$FF
case_num_5: .byte "5",$FF
case_num_6: .byte "6",$FF
case_num_7: .byte "7",$FF
case_num_8: .byte "8",$FF
case_num_9: .byte "9",$FF
case_num_10: .byte "10",$FF
case_num_11: .byte "11",$FF
case_num_12: .byte "12",$FF
case_num_13: .byte "13",$FF
case_num_14: .byte "14",$FF
case_num_15: .byte "15",$FF
case_num_16: .byte "16",$FF
case_num_17: .byte "17",$FF
case_num_18: .byte "18",$FF
case_num_19: .byte "19",$FF
case_num_20: .byte "20",$FF
case_num_21: .byte "21",$FF
case_num_22: .byte "22",$FF

case_num_str_lo: .byte <case_num_1,<case_num_2,<case_num_3,<case_num_4,<case_num_5,<case_num_6,<case_num_7,<case_num_8,<case_num_9,<case_num_10,<case_num_11,<case_num_12,<case_num_13,<case_num_14,<case_num_15,<case_num_16,<case_num_17,<case_num_18,<case_num_19,<case_num_20,<case_num_21,<case_num_22
case_num_str_hi: .byte >case_num_1,>case_num_2,>case_num_3,>case_num_4,>case_num_5,>case_num_6,>case_num_7,>case_num_8,>case_num_9,>case_num_10,>case_num_11,>case_num_12,>case_num_13,>case_num_14,>case_num_15,>case_num_16,>case_num_17,>case_num_18,>case_num_19,>case_num_20,>case_num_21,>case_num_22

; ------------------------------------------------------------
.segment "CHARS"
    .incbin "build/game.chr"

; ------------------------------------------------------------
.segment "VECTORS"
    .addr NMI
    .addr RESET
    .addr IRQ
